# custom-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solver-director
  namespace: psp
imagePullSecrets:
- name: harbor-creds-pull
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solver-director-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solver-director-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solver-director-role
subjects:
- kind: ServiceAccount
  name: solver-director
  namespace: psp